CREATE TYPE weapon_type AS ENUM (
  'Ball & Chain'
	,'Bombs Other'
	,'Boomerang'
	,'Bow'
	,'Dual Sword'
	,'Fire Rod'
	,'Great Sword'
	,'Halberd'
	,'Heavy Shield'
	,'Ice Rod'
	,'Large Bomb'
	,'Lightning Rod'
	,'Light Shield'
	,'Long Sword'
	,'Medium Bomb'
	,'Naginata'
	,'One-Handed Hammer'
	,'Sand Rod'
	,'Short Sword'
	,'Sling'
	,'Small Bomb'
	,'Spear'
	,'Tornado Rod'
	,'Tower Shield'
	,'Two-Handed Hammer'
	,'Unarmed'
	,'Whip'
);
