export const DATABASE_MODULE_OPTIONS = 'DATABASE_MODULE_OPTIONS';
export const DATABASE_FEATURE = 'DATABASE_FEATURE';
export const DATABASE_TEST_OPTIONS = 'DATABASE_TEST_OPTIONS';
export const DATABASE_POOL = 'DATABASE_POOL';
