import { InMemoryDbService } from 'angular-in-memory-web-api';

import { Character } from './Character/character';
import { methods } from './Character/character-methods';

import { Fairy, Gerudo, Goron, Hylian, Rito } from './Races/Races';
import { Attributes } from './Character/Enums/attributes.enum';
import { Magics } from './Character/Enums/magic-skills.enum';
import { Skills } from './Character/Enums/skills.enum';
import { Weapons } from './Character/Enums/weapon-skills.enum';
import { Spell } from './Character/spells';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const EXP = 35100;

    const Bryte = new Fairy('Nayru');
    Bryte.name = 'Bryte';
    Bryte.ac = 20;
    Bryte.flat_footed = 17;
    Bryte.touch = 20;
    Bryte.craftOne = 'Fairy Made Armor';
    Bryte.craftTwo = 'Magic Potions';
    Bryte.profession = 'Armor Smith';
    Bryte.attributes[Attributes['Strength']].value = 11;
    Bryte.attributes[Attributes['Dexterity']].value = 14;
    Bryte.attributes[Attributes['Constitution']].value = 12;
    Bryte.attributes[Attributes['Intelligence']].value = 14;
    Bryte.attributes[Attributes['Wisdom']].value = 25;
    Bryte.attributes[Attributes['Charisma']].value = 14;
    Bryte.health = Bryte.maxHealth = 166;
    Bryte.magic = Bryte.maxMagic = 77;
    Bryte.skills[Skills['CraftOne']].ranks = 3;
    Bryte.skills[Skills['CraftOne']].misc = 5;
    Bryte.skills[Skills['CraftTwo']].ranks = 2;
    Bryte.skills[Skills['Fly']].ranks = 1;
    Bryte.skills[Skills['Knowledge Geography']].ranks = 2;
    Bryte.skills[Skills['Perception']].ranks = 1;
    Bryte.skills[Skills['Perform Music']].ranks = 2;
    Bryte.skills[Skills['Profession']].ranks = 2;
    Bryte.skills[Skills['Sense Motive']].ranks = 3;
    Bryte.weaponSkills[Weapons['Fire Rod']].ranks = 6;
    Bryte.weaponSkills[Weapons['Ice Rod']].ranks = 6;
    Bryte.weaponSkills[Weapons['Lightning Rod']].ranks = 6;
    Bryte.weaponSkills[Weapons['Tornado Rod']].ranks = 9;
    Bryte.weaponSkills[Weapons['Sand Rod']].ranks = 6;
    Bryte.magicSkills[Magics['Din']].ranks = 2;
    Bryte.magicSkills[Magics['Nayru']].ranks = 13;
    Bryte.magicSkills[Magics['Farore']].ranks = 1;
    methods.calcMod(Bryte);
    methods.gainExp(Bryte, EXP);
    const fairyCure = new Spell();
    fairyCure.name = 'Fairy Cure';
    fairyCure.effect = 'Heals target.';
    fairyCure.mpUse = 5;
    fairyCure.damage = 8;
    fairyCure.multiplier = 2;
    fairyCure.diety = 'Nayru';
    fairyCure.modifier = 'Wisdom';
    Bryte.spells = [fairyCure];

    const Rya = new Gerudo();
    Rya.name = 'Rya';
    Rya.ac = 19;
    Rya.flat_footed = 10;
    Rya.touch = 17;
    Rya.health = Rya.maxHealth = 130;
    Rya.magic = Rya.maxMagic = 27;
    Rya.attributes[Attributes['Strength']].value = 24;
    Rya.attributes[Attributes['Dexterity']].value = 24;
    Rya.attributes[Attributes['Constitution']].value = 10;
    Rya.attributes[Attributes['Intelligence']].value = 16;
    Rya.attributes[Attributes['Wisdom']].value = 10;
    Rya.attributes[Attributes['Charisma']].value = 8;
    Rya.skills[Skills['Acrobatics']].ranks = 2;
    Rya.skills[Skills['Perception']].ranks = 5;
    Rya.weaponSkills[Weapons['Short Sword']].ranks = 10;
    Rya.weaponSkills[Weapons['Long Sword']].ranks = 10;
    Rya.weaponSkills[Weapons['Dual Sword']].ranks = 13;
    Rya.weaponSkills[Weapons['Halberd']].ranks = 4;
    Rya.weaponSkills[Weapons['Sling']].ranks = 5;
    Rya.weaponSkills[Weapons['Unarmed']].ranks = 4;
    methods.calcMod(Rya);
    methods.gainExp(Rya, EXP);

    const Greyson = new Goron('Rock Spine');
    Greyson.name = 'Greyson';
    Greyson.craftOne = 'Elemental Bomb';
    Greyson.health = Greyson.maxHealth = 140;
    Greyson.magic = Greyson.maxMagic = 19;
    Greyson.attributes[Attributes['Strength']].value = 25;
    Greyson.attributes[Attributes['Dexterity']].value = 14;
    Greyson.attributes[Attributes['Constitution']].value = 24;
    Greyson.attributes[Attributes['Intelligence']].value = 12;
    Greyson.attributes[Attributes['Wisdom']].value = 12;
    Greyson.attributes[Attributes['Charisma']].value = 11;
    Greyson.magicSkills[Magics['Din']].ranks = 2;
    Greyson.magicSkills[Magics['Nayru']].ranks = 2;
    Greyson.magicSkills[Magics['Farore']].ranks = 2;
    Greyson.ac = 17;
    Greyson.flat_footed = 10;
    Greyson.touch = 17;
    Greyson.skills[Skills['Acrobatics']].ranks = 5;
    Greyson.skills[Skills['Climb']].ranks = 2;
    Greyson.skills[Skills['Handle Animal']].ranks = 3;
    Greyson.skills[Skills['CraftOne']].misc = 3;
    Greyson.skills[Skills['Stealth']].ranks = 2;
    Greyson.weaponSkills[Weapons['Tower Shield']].ranks = 5;
    Greyson.weaponSkills[Weapons['One-Handed Hammer']].ranks = 10;
    Greyson.weaponSkills[Weapons['Two-Handed Hammer']].ranks = 2;
    Greyson.weaponSkills[Weapons['Small Bomb']].ranks = 4;
    Greyson.weaponSkills[Weapons['Medium Bomb']].ranks = 4;
    Greyson.weaponSkills[Weapons['Large Bomb']].ranks = 3;
    Greyson.weaponSkills[Weapons['Bombs Other']].ranks = 3;
    Greyson.weaponSkills[Weapons['Unarmed']].ranks = 13;
    methods.calcMod(Greyson);
    methods.gainExp(Greyson, EXP);

    const Golo = new Hylian('Farmer');
    Golo.name = 'Golo';
    Golo.health = Golo.maxHealth = 76;
    Golo.magic = Golo.maxMagic = 19;
    Golo.attributes[0].value = 23;
    Golo.attributes[1].value = 12;
    Golo.attributes[2].value = 22;
    Golo.attributes[3].value = 6;
    Golo.attributes[4].value = 6;
    Golo.attributes[5].value = 18;
    Golo.ac = 14;
    Golo.flat_footed = 13;
    Golo.touch = 11;
    Golo.weaponSkills[0].ranks = 5;
    Golo.skills[5].ranks = 3;
    Golo.skills[9].ranks = 1;
    Golo.skills[22].ranks = 4;
    Golo.skills[29].ranks = 2;
    methods.calcMod(Golo);
    methods.gainExp(Golo, EXP);

    const characters: Character[] = [Bryte, Rya, Greyson, Golo];
    return { characters };
  }
}
