export enum Skills {
  'Accrobatics',
  'Appraise',
  'Bluff',
  'Climb',
  'CraftOne',
  'CraftTwo',
  'Diplomacy',
  'EscapeArtist',
  'Fly',
  'Handle Animal',
  'Heal',
  'Intimidate',
  'Knowledge Geography',
  'Knowledge History',
  'Knowledge Language',
  'Knowledge Local',
  'Knowledge Magic',
  'Knowledge Monsters',
  'Knowledge Nature',
  'Knowledge Nobility',
  'Knowledge Religion',
  'Perception',
  'Perform Music',
  'Perform Other',
  'Profession',
  'Ride',
  'Sense Motive',
  'Sleight of Hand',
  'Stealth',
  'Survival',
  'Swim'
}
