export enum Weapons {
  'Short Swords',
  'Long Swords',
  'Dual Swords',
  'Great Swords',
  'Light Shields',
  'Heavy Shields',
  'Tower Shields',
  'One-Handed Hammers',
  'Two-Handed Hammers',
  'Spears',
  'Halberds',
  'Nagitnatas',
  'Boomerangs',
  'Sligs',
  'Bows',
  'Small Bombs',
  'Medium Bombs',
  'Large Bombs',
  'Bombs Other',
  'Fire Rods',
  'Ice Rods',
  'Lightning Rods',
  'Tornado Rods',
  'Sand Rods',
  'Whips',
  'Ball & Chains',
  'Unarmed'
}
