export enum Weapons {
  'Short Sword',
  'Long Sword',
  'Dual Sword',
  'Great Sword',
  'Light Shield',
  'Heavy Shield',
  'Tower Shield',
  'One-Handed Hammer',
  'Two-Handed Hammer',
  'Spear',
  'Halberd',
  'Nagitnata',
  'Boomerang',
  'Sling',
  'Bow',
  'Small Bomb',
  'Medium Bomb',
  'Large Bomb',
  'Bombs Other',
  'Fire Rod',
  'Ice Rod',
  'Lightning Rod',
  'Tornado Rod',
  'Sand Rod',
  'Whip',
  'Ball & Chain',
  'Unarmed'
}
