export enum WeaponType {
  'Ball & Chain' = 'Ball & Chain',
  'Bombs Other' = 'Bombs Other',
  'Boomerang' = 'Boomerang',
  'Bow' = 'Bow',
  'Dual Sword' = 'Dual Sword',
  'Fire Rod' = 'Fire Rod',
  'Great Sword' = 'Great Sword',
  'Halberd' = 'Halberd',
  'Heavy Shield' = 'Heavy Shield',
  'Ice Rod' = 'Ice Rod',
  'Large Bomb' = 'Large Bomb',
  'Lightning Rod' = 'Lightning Rod',
  'Long Sword' = 'Long Sword',
  'Medium Bomb' = 'Medium Bomb',
  'Naginata' = 'Naginata',
  'One-Handed Hammer' = 'One-Handed Hammer',
  'Sand Rod' = 'Sand Rod',
  'Short Sword' = ' Short Sword',
  'Sling' = 'Sling',
  'Small Bomb' = 'Small Bomb',
  'Spear' = 'Spear',
  'Tornado Rod' = 'Tornado Rod',
  'Unarmed' = 'Unarmed',
  'Whip' = 'Whip'
}
