CREATE TABLE character (
  id VARCHAR(12) PRIMARY KEY DEFAULT createId('00C'),
  name TEXT NOT NULL,
  player_id VARCHAR(12) NOT NULL REFERENCES player (id),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  created_by VARCHAR(12) NOT NULL REFERENCES player (id),
  last_modified_by VARCHAR(12) NOT NULL REFERENCES player (id),
  last_modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  race character_race NOT NULL,
  strength INTEGER NOT NULL CHECK (strength > 6),
  dexterity INTEGER NOT NULL CHECK (dexterity > 6),
  constitution INTEGER NOT NULL CHECK (constitution > 6),
  intelligence INTEGER NOT NULL CHECK (intelligence > 6),
  wisdom INTEGER NOT NULL CHECK (wisdom > 6),
  charisma INTEGER NOT NULL CHECK (charisma > 6),
  health_max INTEGER NOT NULL CHECK (health_max > 0),
  magic_max INTEGER NOT NULL CHECK (magic_max > 0),
  health INTEGER NOT NULL CHECK (health < health_max),
  magic INTEGER NOT NULL CHECK (magic < magic_max),
  experience INTEGER NOT NULL CHECK (experience > 0),
  level INTEGER NOT NULL CHECK (level > 0),
  craft_one VARCHAR,
  craft_two VARCHAR,
  profession VARCHAR,
  performance VARCHAR
);
